name: 'Brisk - Setup Brisk'
description: 'Sets up Brisk CLI in your GitHub Actions workflow.'
author: 'Brisk Inc.'
inputs:
  brisk_version:
    description: 'The version of Brisk CLI to install. A value of `latest` will install the latest version of Brisk CLI. Defaults to `latest`.'
    default: 'latest'
    required: false
  api_token:
    description: 'The Brisk API token to use for authentication. If not specified, the action will try to read the token from the `BRISK_APITOKEN` environment variable.'
    required: false    
  api_key:
    description: 'The Brisk API key to use for authentication. If not specified, the action will try to read the key from the `BRISK_APIKEY` environment variable.'
    required: false
  config_file:
    description: 'The path to the Brisk configuration file. If not specified, the action will try to read the path from the `BRISK_PROJECT_CONFIG_FILE` environment variable.'
    required: false
runs:
  using: 'node16'
  main: 'dist/src/index.js'
branding:
  icon: 'zap'
  color: 'blue'